.ubuntu: &ubuntu
  image: wireshark/wireshark-ubuntu-dev
  retry: 1
  before_script:
    - apt-get update -qq
    - ./tools/debian-setup.sh --install-optional -y
    - mkdir build
    - cd build
.rpm: &rpm
  artifacts:
    paths:
      - build/packaging/rpm/RPMS
    expire_in: 3 days
gcc-5:
  <<: *ubuntu
  script:
    - ../tools/debian-setup.sh --install-optional ninja-build gcc-5 g++-5 -y
    - cmake -GNinja -DCMAKE_C_COMPILER=gcc-5 -DCMAKE_CXX_COMPILER=g++-5 ..
    - ninja
gcc-6:
  <<: *ubuntu
  script:
    - ../tools/debian-setup.sh --install-optional ninja-build  gcc-6 g++-6 -y
    - cmake -GNinja -DCMAKE_C_COMPILER=gcc-6 -DCMAKE_CXX_COMPILER=g++-6 ..
    - ninja
gcc-7:
  <<: *ubuntu
  script:
    - ../tools/debian-setup.sh --install-optional ninja-build  gcc-7 g++-7 -y
    - cmake -GNinja -DCMAKE_C_COMPILER=gcc-7 -DCMAKE_CXX_COMPILER=g++-7 ..
    - ninja
gcc-8:
  <<: *ubuntu
  script:
    - ../tools/debian-setup.sh --install-optional ninja-build  gcc-8 g++-8 -y
    - cmake -GNinja -DCMAKE_C_COMPILER=gcc-8 -DCMAKE_CXX_COMPILER=g++-8 ..
    - ninja
gcc-8-nopcap:
  <<: *ubuntu
  script:
    - ../tools/debian-setup.sh --install-optional ninja-build  gcc-8 g++-8 -y
    - cmake -GNinja -DENABLE_PCAP=OFF -DCMAKE_C_COMPILER=gcc-8 -DCMAKE_CXX_COMPILER=g++-8 ..
    - ninja
clang-3.9:
  <<: *ubuntu
  script:
    - ../tools/debian-setup.sh --install-optional ninja-build  clang-3.9 -y
    - cmake -GNinja -DCMAKE_C_COMPILER=clang-3.9 -DCMAKE_CXX_COMPILER=clang++-3.9 ..
    - ninja
clang-4.0:
  <<: *ubuntu
  script:
    - ../tools/debian-setup.sh --install-optional ninja-build  clang-4.0 -y
    - cmake -GNinja -DCMAKE_C_COMPILER=clang-4.0 -DCMAKE_CXX_COMPILER=clang++-4.0 -DCMAKE_C_FLAGS=-Wframe-larger-than=20000 ..
    - ninja
clang-5.0:
  <<: *ubuntu
  script:
    - ../tools/debian-setup.sh --install-optional ninja-build  clang-5.0 -y
    - cmake -GNinja -DCMAKE_C_COMPILER=clang-5.0 -DCMAKE_CXX_COMPILER=clang++-5.0 -DCMAKE_C_FLAGS=-Wframe-larger-than=20000 ..
    - ninja
clang-6.0:
  <<: *ubuntu
  script:
    - ../tools/debian-setup.sh --install-optional ninja-build  clang-6.0 -y
    - cmake -GNinja -DCMAKE_C_COMPILER=clang-6.0 -DCMAKE_CXX_COMPILER=clang++-6.0 -DCMAKE_C_FLAGS=-Wframe-larger-than=20000 ..
    - ninja
clang-7:
  <<: *ubuntu
  script:
     - ../tools/debian-setup.sh --install-optional ninja-build clang-7 -y
     - cmake -GNinja -DCMAKE_C_COMPILER=clang-7  -DCMAKE_CXX_COMPILER=clang++-7 -DCMAKE_C_FLAGS=-Wframe-larger-than=20000 ..
     - ninja
clang-7-nopcap:
  <<: *ubuntu
  script:
    - ../tools/debian-setup.sh --install-optional ninja-build clang-7 -y
    - cmake -GNinja -DENABLE_PCAP=OFF -DCMAKE_C_COMPILER=clang-7 -DCMAKE_CXX_COMPILER=clang++-7 -DCMAKE_C_FLAGS=-Wframe-larger-than=20000 ..
    - ninja
rpm-centos-7:
  <<: *rpm
  image: centos:7
  script:
    - yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    - tools/rpm-setup.sh --install-optional -y
    - mkdir build
    - cd build
    - cmake3 -GNinja ..
    - ninja-build rpm-package
rpm-opensuse-42.3:
  <<: *rpm
  image: opensuse/leap:42.3
  script:
    - zypper --non-interactive install update-desktop-files
    - tools/rpm-setup.sh --install-optional ruby
    - gem install asciidoctor
    - mkdir build
    - cd build
    - cmake -GNinja ..
    - ninja rpm-package
rpm-fedora-28:
  <<: *rpm
  image: fedora:28
  script:
    - dnf upgrade -y
    - tools/rpm-setup.sh --install-optional -y
    - mkdir build
    - cd build
    - cmake3 -GNinja ..
    - ninja-build rpm-package
after_script:
  - for builddir in build/packaging/rpm/BUILD/wireshark-*/build build/packaging/rpm/BUILD/wireshark-* build; do [ ! -d "$builddir" ] || break; done
  - if [ "$CI_JOB_NAME" = "rpm-opensuse-42.3" ]; then export LD_LIBRARY_PATH=$builddir/run; fi
  - if [ -f $builddir/run/tshark ]; then $builddir/run/tshark --version; fi
